### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by thomasfl** [ekynoxe/Racetiming#1]
Is there a way to use this? Or is there too much missing? I was only able to register a race on localhost:300/races

**Comment by ekynoxe** [comment]
Hi Thomas, no, this is not an active project, and I've had to move on to other things. I'll delete this repository, as it's not going to be worked on.

**Comment by thomasfl** [comment]
Ok! It's a pity. I would really have liked a system that was easy to hack.

**Comment by ekynoxe** [comment]
I know, that's initially why I started this. But lack of time made me abandon it.
I'll be writing something new soon, but most likely as part of a business offering.
I'm literally just back from a day of timing an aquathlon and a triathlon with pen, paper, and a giant excel spreadsheet... Not pretty!

So I know your pain.
